<?php

namespace Yuno\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BannerGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BannerGroupRepository extends EntityRepository
{
    public function getBannerCountsForUser(User $user)
    {
        return $this->getEntityManager()->createQuery('Select bg.id, Count(b.id) As total From MainBundle:BannerGroup bg Index By bg.id Left Join bg.banners b Left Join b.site s Where s.user = :user Group By bg')
          ->setParameter('user', $user)
          ->execute();
    }
}
