<?php

namespace Yuno\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * IpBanRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IpBanRepository extends EntityRepository
{
}
